# Generated by Django 5.1.3 on 2024-11-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produkty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produkt",
            name="grupa_towarowa",
            field=models.CharField(default="Nieznana", max_length=100),
            preserve_default=False,
        ),
    ]
