# Generated by Django 5.1.3 on 2024-11-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produkty", "0002_produkt_grupa_towarowa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sprzedaz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("ilosc_sztuk", models.IntegerField()),
                ("data_sprzedazy", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
