# Generated by Django 5.1.3 on 2024-11-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produkty", "0004_rename_ilosc_sztuk_sprzedaz_liczba_sztuk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produkt",
            name="marka",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
