# Generated by Django 5.1.3 on 2024-12-05 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produkty", "0005_produkt_marka"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
                ("opis", models.TextField()),
                ("minimalna_liczba_sztuk", models.IntegerField()),
                (
                    "premia_za_minimalna_liczbe",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "premia_za_dodatkowa_liczbe",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("data_rozpoczecia", models.DateField()),
                ("data_zakonczenia", models.DateField()),
                ("produkty", models.ManyToManyField(to="produkty.produkt")),
            ],
        ),
        migrations.AddField(
            model_name="sprzedaz",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="produkty.task",
            ),
        ),
    ]
