# Generated by Django 5.1.3 on 2024-12-19 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produkty", "0006_task_sprzedaz_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrupaProduktowa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Marka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ekspozycja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liczba_sztuk", models.PositiveIntegerField(default=0)),
                (
                    "grupa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produkty.grupaproduktowa",
                    ),
                ),
                (
                    "marka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="produkty.marka"
                    ),
                ),
            ],
        ),
    ]
