# Generated by Django 5.1.3 on 2024-12-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produkty", "0007_grupaproduktowa_marka_ekspozycja"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ekspozycja",
            old_name="liczba_sztuk",
            new_name="liczba",
        ),
    ]
