# Generated by Django 5.1.3 on 2025-08-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produkty", "0010_klientcounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="mnoznik_mix",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Mnożnik dla zadań typu mix",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="prog_mix",
            field=models.PositiveIntegerField(
                blank=True, help_text="Próg dla zadań typu mix", null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="typ",
            field=models.CharField(
                choices=[
                    ("MIX_PROWIZJA", "Mix prowizja"),
                    ("MIX_MNOZNIK", "Mix mnożnik"),
                    ("KONKRETNE_MODELE", "Konkretne modele"),
                ],
                default="KONKRETNE_MODELE",
                max_length=20,
            ),
        ),
    ]
