# Generated by Django 5.1.3 on 2025-11-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0011_task_mnoznik_mix_task_prog_mix_task_typ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='premia_za_dodatkowa_liczbe',
            new_name='prog_premia_1',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='premia_za_minimalna_liczbe',
            new_name='prog_premia_2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='minimalna_liczba_sztuk',
        ),
        migrations.RemoveField(
            model_name='task',
            name='mnoznik_mix',
        ),
        migrations.RemoveField(
            model_name='task',
            name='mnoznik_stawki',
        ),
        migrations.RemoveField(
            model_name='task',
            name='prog_mix',
        ),
        migrations.RemoveField(
            model_name='task',
            name='typ',
        ),
        migrations.AddField(
            model_name='task',
            name='prog_ilosc_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='prog_ilosc_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='produkty',
            field=models.ManyToManyField(blank=True, related_name='zadania', to='produkty.produkt'),
        ),
    ]
