# Generated by Django 5.1.3 on 2025-11-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0012_rename_premia_za_dodatkowa_liczbe_task_prog_premia_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('data_start', models.DateField()),
                ('data_koniec', models.DateField()),
                ('prog_1', models.PositiveIntegerField(blank=True, null=True)),
                ('prog_2', models.PositiveIntegerField(blank=True, null=True)),
                ('produkty', models.ManyToManyField(blank=True, related_name='cele', to='produkty.produkt')),
            ],
        ),
    ]
