# Generated by Django 5.1.3 on 2025-11-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0013_zadanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadanie',
            name='prog_1_premia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zadanie',
            name='prog_2_premia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zadanie',
            name='target',
            field=models.CharField(choices=[('ilosc', 'Ilość'), ('wartosc', 'Wartość')], default='ilosc', max_length=10),
        ),
    ]
