# Generated by Django 5.1.3 on 2025-11-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0017_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzedaz',
            name='prowizja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
