# Generated by Django 5.1.3 on 2025-12-12 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0018_sprzedaz_prowizja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klientcounter',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sprzedaz',
            name='data_sprzedazy',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
