# Generated by Django 5.1.3 on 2026-05-12 20:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0019_alter_klientcounter_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PunktChecklisty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
                ('aktywny', models.BooleanField(default=True)),
                ('kolejnosc', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['kolejnosc'],
            },
        ),
        migrations.CreateModel(
            name='DzienPracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('czas_otwarcia', models.DateTimeField(auto_now_add=True)),
                ('czas_zamkniecia', models.DateTimeField(blank=True, null=True)),
                ('notatka_sprzedaz', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'data')},
            },
        ),
        migrations.CreateModel(
            name='GrafikPracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('godzina_rozpoczecia', models.TimeField(blank=True, null=True)),
                ('godzina_zakonczenia', models.TimeField(blank=True, null=True)),
                ('suma_godzin', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notatka', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('user', 'data')},
            },
        ),
        migrations.CreateModel(
            name='OdpowiedzChecklisty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wykonano', models.BooleanField(default=False)),
                ('dzien_pracy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odpowiedzi_checklisty', to='produkty.dzienpracy')),
                ('punkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkty.punktchecklisty')),
            ],
            options={
                'unique_together': {('dzien_pracy', 'punkt')},
            },
        ),
    ]
