# Generated by Django 5.1.3 on 2026-05-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0020_punktchecklisty_dzienpracy_grafikpracy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podpowiedz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('tresc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='zadanie',
            name='target',
            field=models.CharField(blank=True, choices=[('ilosc', 'Ilość'), ('wartosc', 'Wartość')], default='ilosc', max_length=10),
        ),
        migrations.AlterField(
            model_name='zadanie',
            name='typ',
            field=models.CharField(blank=True, choices=[('MIX_PROWIZJA', 'Mix prowizja'), ('MIX_MNOZNIK', 'Mix mnożnik'), ('KONKRETNE_MODELE', 'Konkretne modele')], default='KONKRETNE_MODELE', max_length=20),
        ),
        migrations.CreateModel(
            name='Funkcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('opis', models.TextField(blank=True, null=True)),
                ('produkty', models.ManyToManyField(blank=True, related_name='funkcje', to='produkty.produkt')),
            ],
        ),
    ]
