# Generated by Django 5.1.3 on 2026-05-31 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0021_podpowiedz_alter_zadanie_target_alter_zadanie_typ_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150, verbose_name='Nazwa grupy')),
                ('aktywna', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('kolejnosc', models.IntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'ordering': ['kolejnosc', 'nazwa'],
            },
        ),
        migrations.CreateModel(
            name='TopSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150, verbose_name='Nazwa podgrupy')),
                ('kolejnosc', models.IntegerField(default=0, verbose_name='Kolejność')),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgrupy', to='produkty.topgroup')),
            ],
            options={
                'ordering': ['kolejnosc', 'nazwa'],
            },
        ),
        migrations.CreateModel(
            name='TopListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycja', models.PositiveIntegerField(verbose_name='Pozycja')),
                ('model_tekst', models.CharField(max_length=150, verbose_name='Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_listy', to=settings.AUTH_USER_MODEL)),
                ('subgrupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wpisy', to='produkty.topsubgroup')),
            ],
            options={
                'ordering': ['pozycja'],
                'unique_together': {('user', 'subgrupa', 'pozycja')},
            },
        ),
    ]
