# Generated by Django 5.1.3 on 2026-07-24 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0022_topgroup_topsubgroup_toplistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alejka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150, verbose_name='Nazwa alejki')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('kolejnosc', models.IntegerField(default=0, verbose_name='Kolejność na mapie')),
                ('aktywna', models.BooleanField(default=True, verbose_name='Aktywna')),
            ],
            options={
                'verbose_name': 'Alejka',
                'verbose_name_plural': 'Alejki',
                'ordering': ['kolejnosc', 'nazwa'],
            },
        ),
        migrations.CreateModel(
            name='MiejsceProduktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strona', models.CharField(choices=[('L', 'Lewa'), ('P', 'Prawa')], default='L', max_length=1)),
                ('pozycja', models.PositiveIntegerField(default=0, verbose_name='Pozycja w alejce')),
                ('alejka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miejsca', to='produkty.alejka')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miejsca', to='produkty.produkt')),
            ],
            options={
                'verbose_name': 'Miejsce produktu',
                'verbose_name_plural': 'Miejsca produktów',
                'ordering': ['strona', 'pozycja'],
            },
        ),
    ]
