# Generated by Django 5.1.3 on 2026-07-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0023_alejka_miejsceproduktu'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='data_aktualizacji',
            field=models.DateField(blank=True, null=True, verbose_name='Data ostatniej aktualizacji'),
        ),
    ]
