# Generated by Django 5.1.3 on 2026-07-28 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0024_produkt_data_aktualizacji'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObiektMapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150, verbose_name='Nazwa')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('typ', models.CharField(choices=[('WYKLUCZENIE', 'Wykluczenie / strefa'), ('STANOWISKO', 'Stanowisko'), ('KASA', 'Kasa'), ('MAGAZYN', 'Magazyn / zaplecze'), ('INNE', 'Inne')], default='WYKLUCZENIE', max_length=20, verbose_name='Typ')),
                ('pozycja_x', models.IntegerField(default=0, verbose_name='Pozycja X (kratka)')),
                ('pozycja_y', models.IntegerField(default=0, verbose_name='Pozycja Y (kratka)')),
                ('szerokosc', models.PositiveIntegerField(default=3, verbose_name='Szerokość (w kratkach)')),
                ('wysokosc', models.PositiveIntegerField(default=3, verbose_name='Wysokość (w kratkach)')),
                ('aktywny', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Obiekt mapy',
                'verbose_name_plural': 'Obiekty mapy',
                'ordering': ['nazwa'],
            },
        ),
        migrations.AddField(
            model_name='alejka',
            name='dlugosc',
            field=models.PositiveIntegerField(default=8, help_text='Im większa wartość, tym dłuższa alejka na mapie.', verbose_name='Długość (w kratkach)'),
        ),
        migrations.AddField(
            model_name='alejka',
            name='orientacja',
            field=models.CharField(choices=[('V', 'Pionowa'), ('H', 'Pozioma')], default='V', max_length=1, verbose_name='Orientacja'),
        ),
        migrations.AddField(
            model_name='alejka',
            name='pozycja_x',
            field=models.IntegerField(default=0, verbose_name='Pozycja X (kratka)'),
        ),
        migrations.AddField(
            model_name='alejka',
            name='pozycja_y',
            field=models.IntegerField(default=0, verbose_name='Pozycja Y (kratka)'),
        ),
        migrations.AddField(
            model_name='miejsceproduktu',
            name='marka_tekst',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marka (spoza katalogu)'),
        ),
        migrations.AddField(
            model_name='miejsceproduktu',
            name='model_tekst',
            field=models.CharField(blank=True, max_length=150, verbose_name='Model (spoza katalogu)'),
        ),
        migrations.AlterField(
            model_name='miejsceproduktu',
            name='produkt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miejsca', to='produkty.produkt'),
        ),
    ]
