# Generated by Django 5.1.3 on 2026-07-29 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0026_rozstaw_istniejace_alejki'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sprzedaz',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprzedaze', to=settings.AUTH_USER_MODEL, verbose_name='Sprzedawca'),
        ),
        migrations.CreateModel(
            name='Hala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150, verbose_name='Nazwa hali')),
                ('opis', models.TextField(blank=True, verbose_name='Opis / lokalizacja')),
                ('aktywna', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('pracownicy', models.ManyToManyField(blank=True, related_name='hale', to=settings.AUTH_USER_MODEL, verbose_name='Pracownicy')),
            ],
            options={
                'verbose_name': 'Hala',
                'verbose_name_plural': 'Hale',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='TargetHali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('MIESIAC', 'Miesięczny'), ('KWARTAL', 'Kwartalny')], default='MIESIAC', max_length=10, verbose_name='Typ targetu')),
                ('rok', models.PositiveIntegerField(verbose_name='Rok')),
                ('kwartal', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], verbose_name='Kwartał')),
                ('miesiac', models.PositiveSmallIntegerField(blank=True, help_text='Wypełniane tylko dla targetu miesięcznego.', null=True, verbose_name='Miesiąc')),
                ('cel_beko', models.PositiveIntegerField(default=0, verbose_name='Cel Beko (szt.)')),
                ('cel_whirlpool', models.PositiveIntegerField(default=0, verbose_name='Cel Whirlpool (szt.)')),
                ('hala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targety', to='produkty.hala')),
            ],
            options={
                'verbose_name': 'Target hali',
                'verbose_name_plural': 'Targety hal',
                'ordering': ['-rok', '-kwartal', 'miesiac'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('miesiac__isnull', False)), fields=('hala', 'rok', 'miesiac'), name='unikalny_target_miesieczny'), models.UniqueConstraint(condition=models.Q(('miesiac__isnull', True)), fields=('hala', 'rok', 'kwartal'), name='unikalny_target_kwartalny')],
            },
        ),
    ]
